name:                fashion
version:             0.1.0.0
github:              "isovector/fashion"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2019 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/fashion#readme>

dependencies:
- base >= 4.7 && < 5
- diagrams
- diagrams-cairo
- diagrams-core >= 1.1.0.3
- diagrams-lib
- diagrams-contrib

ghc-options:
  - -Wall
  - -fno-warn-missing-signatures
  - -fno-warn-type-defaults

default-extensions:
  - TypeApplications
  - NoMonomorphismRestriction
  - GADTs
  - FlexibleContexts
  - ViewPatterns

library:
  source-dirs: src

# executables:
#  exe:
#    main:                Main.hs
#    source-dirs:         app
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - fashion

