name:                fashion
version:             0.1.0.0
github:              "isovector/fashion"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2019 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/fashion#readme>

dependencies:
- base >= 4.7 && < 5
- diagrams
- diagrams-svg
- diagrams-lib
- diagrams-contrib
- suavemente

library:
  source-dirs: src
